### ISSUE TITLE
payment-funded.php

### ISSUE THREAD

**Issue by nrayson** [mitadminn/InstantJob#15]
1. Potential SQL injection vulnerabilities, make sure the variables are sanitize before use. e.g. ``` $plan_is```
2. CSRF vulnerabilities, there is no CSRF token being used. Potential security issue, attacker can trick a user into submitting a request that they didn't intend.
3. Session security - you're using ```$_SESSION['Userid']``` without any checks to see if the session is valid or is the user is authenticated?
4. Also, I mentioned this before. Please use semantically correct HTML for list ```<ul><li>```
![Screenshot 2023-12-03 at 6 06 42 PM](https://github.com/mitadminn/InstantJob/assets/74104962/2dd3354d-6b26-434d-aab3-20802cb84b98)
5. Use ```<section>``` NOT ```<Section>```

**Comment by akhilnolke** [comment]
(<ul><li>)HTML fixed

**Comment by mitadminn** [comment]
Fixed
