### ISSUE TITLE
[Global] - Remove all empty inline styles

### ISSUE THREAD

**Issue by nrayson** [mitadminn/InstantJob#21]
![Screenshot 2023-12-03 at 6 26 42 PM](https://github.com/mitadminn/InstantJob/assets/74104962/81b7e908-a57c-4bbd-bd02-de79d5c2eda6)
![Screenshot 2023-12-03 at 6 27 55 PM](https://github.com/mitadminn/InstantJob/assets/74104962/1d8c6ed7-248d-45f8-b555-836c24c7defd)

**Comment by akhilnolke** [comment]
fixed
