### ISSUE TITLE
single-statement.php

### ISSUE THREAD

**Issue by nrayson** [mitadminn/InstantJob#25]
Is this being used?

If it is, please make sure the receipt number is updated, and there's a typo for the text, "Receipt".
![Screenshot 2023-12-05 at 8 09 48 AM](https://github.com/mitadminn/InstantJob/assets/74104962/d83d0ca2-190f-43e1-a71c-20f5475d5dc0)

Make sure the address is formatted correctly with proper letter casing and spelling.

**Comment by nrayson** [comment]
@mitadminn receipt number is not dynamic? It's hard-coded now.

**Comment by mitadminn** [comment]
Done
