### ISSUE TITLE
Database connection credentials

### ISSUE THREAD

**Issue by nrayson** [mitadminn/InstantJob#28]
I've seen this in a few places, I don't think it's best practice nor it's secure.
![Screenshot 2023-12-05 at 8 27 15 AM](https://github.com/mitadminn/InstantJob/assets/74104962/f53e2c8e-40d8-4e80-be56-b425ef641401)

Please use environment variables for sensitive data, or some configuration file outside the web root for storing the db name and password.

Also, consider using a centralise db connection, rather than repeating the code in multiple files then just "require_once"

**Comment by mitadminn** [comment]
Fixed
