### ISSUE TITLE
discussion.php

### ISSUE THREAD

**Issue by nrayson** [mitadminn/InstantJob#4]
1. Have you consider using web sockets instead of doing frequent AJAX polling? 

2. the AJAX call for loading chat notifications  (load_userchat_notification()) is set up twice in the JavaScript code. It's first defined within the $(document).ready(function(){...}) and then again outside of it.
- define this once then call it whenever you need. You can define it  outside of the document.ready, and just call it inside if needed on page load.

3. Why doesn't this look identical?
![Screenshot 2023-12-03 at 4 10 31 PM](https://github.com/mitadminn/InstantJob/assets/74104962/e5c3673c-5146-4f96-baf6-88de8e91f561)
also, give it a proper name instead of "Modal title"

4. Fix spelling reciever = receiver
![Screenshot 2023-12-03 at 4 12 31 PM](https://github.com/mitadminn/InstantJob/assets/74104962/c1c4abb4-afba-4cf6-8422-f42926712733)

5. Fill upload validation check, please use server-side validation instead. Use MIME types, there should be an allowed list. e.g.
```$allowedMimeTypes = ['image/jpeg', 'image/png', 'application/pdf', /* other allowed types */];```
You do it in PHP, go use chatGPT to figure out.

This page is a bloody pain in the ass to read. There is no proper separation of function, style and HTML.

**Comment by mitadminn** [comment]
Fix spelling reciever = receiver this in code only not showing anywhere we used same veriable in multiple files so i need to change on all so i keep it like that

**Comment by mitadminn** [comment]
point 2 fixed
