### ISSUE TITLE
edit-service.php

### ISSUE THREAD

**Issue by nrayson** [mitadminn/InstantJob#8]
1. The same redundant character count code, it doesn't the same thing. Just write a generic function.
![Screenshot 2023-12-03 at 4 53 28 PM](https://github.com/mitadminn/InstantJob/assets/74104962/d3e977cf-6d55-44aa-b252-535e09f1bb42)

2. Same SQL Injection vulnerability, see the line with ```$id = $_GET['id'];``` go use prepared statements or sanitize the input.

**Comment by akhilnolke** [comment]
point 1 fixed

**Comment by mitadminn** [comment]
Done

**Comment by nrayson** [comment]
You said point 1 is fixed, no it's not fixed.
![Screenshot 2023-12-20 at 6 40 27 PM](https://github.com/mitadminn/InstantJob/assets/74104962/45c8e6f8-ce0c-47fd-ae4a-500718e6c4bc)

**Comment by mitadminn** [comment]
fixed
