### ISSUE TITLE
fund.php

### ISSUE THREAD

**Issue by nrayson** [mitadminn/InstantJob#9]
1. Duplicate Proceed button in the code? Is this a mistake?
![Screenshot 2023-12-03 at 5 05 27 PM](https://github.com/mitadminn/InstantJob/assets/74104962/431053c5-204c-4f26-8cbb-dec932f9721d)

2. Why can't you use semantically correct HTML for list?
![Screenshot 2023-12-03 at 5 06 36 PM](https://github.com/mitadminn/InstantJob/assets/74104962/411e304b-149d-44bf-a909-bd7e4678eb83)
Redo this using ```<ul><li>```

**Comment by akhilnolke** [comment]
fixed
